### ISSUE TITLE
Feature request: requesting books

### ISSUE THREAD

**Issue by MatMoore** [alphagov/anthology#1]
- If someone already has a book checked out, it would be great to be able to say "I would like to read this next, tell me when it's available again" (I guess you can talk to people outside of the app, but the app could make it easier, particularly when there are multiple copies on loan)

- If the library doesn't have a book, we should be able to request it, so we can periodically review and order in stuff that would be useful to the community (again, there may be some way to do this outside of the app, but I don't know how, and the app could actually notify you when the book is available)

**Comment by issyl0** [comment]
I only just noticed this. So evidently it wasn't. The canonical source for the GDS Library is at https://github.com/issyl0/anthology. I'll close this and re-raise it over there (you can't transfer issues across orgs).
